### ISSUE TITLE
KL reduction calculation

### ISSUE THREAD

**Issue by Schopenhauer-loves-Hegel** [p-lambda/dsir#11]
How do you calculate the KL reduction for dataset feature distribution?

**Comment by sangmichaelxie** [comment]
See section I of the Appendix in the paper (https://arxiv.org/pdf/2302.03169) and Section 6 of the paper; essentially compute the hashed ngram distributions for the target, raw, and selected data (3 vectors of the same size), then compute the KL divergence, for example between target and raw, by `kl_tgt_raw = np.inner(target, np.log(target + 1e-10) - np.log(raw + 1e-10))`. We computed the hashed ngram distributions with 100k random samples from each dataset. Finally the KL reduction is a difference between two KL divergences.
