### ISSUE TITLE
error occurs in `compute_domain_idxs` 

### ISSUE THREAD

**Issue by BeachWang** [p-lambda/dsir#6]
Hi,

I tried to run the pipeline in `experimental`. However, an error occured in `compute_domain_idxs` when I ran the resample. It seems to be that `ds_path` is used as a Path or string, but it is a list.

<img width="693" alt="截屏2023-11-30 下午12 38 36" src="https://github.com/p-lambda/dsir/assets/22676348/deaf9692-dd70-4b2f-accd-2039e4b3f94f">

**Comment by sangmichaelxie** [comment]
Thanks, just made a commit (a085821) that should fix it. Let me know if there are more issues.

Btw, I think this pipeline could be run much faster using the library code in the outer directory - after preprocessing into chunks, you can use `HashedNgramDSIR` on that preprocessed data with the `tokenizer=word_tokenize` argument. The quality filter can be implemented by overriding `get_perexample_metadata` and `perexample_metadata_filter` (also in my experience, the default length filter that's already implemented is the main one that has an effect).
